spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:tcp://localhost/~/db;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  security:
    secretKey: fireWood

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
#        default_batch_fetch_size: 100
#    open-in-view: false


api:
  kakao:
    client_id: bf0e93a698d2bb02bfb634e3f662747c
    response_type: code
    kakao_authorize_request_uri: https://kauth.kakao.com/oauth/authorize
    kakao_login_request_uri: https://kauth.kakao.com/oauth/token
    kakao_privacy_request_uri: https://kapi.kakao.com/v2/user/me
    kakao_logout_request_uri: https://kauth.kakao.com/oauth/logout
    join_request_uri: http://localhost:8080/kakao/join
    login_request_uri: http://localhost:8080/kakao/login
    logout_redirect_uri: http://localhost:8080/kakao/login

logging:
  level:
    org.hibernate.SQL: debug

