spring:
  profiles:
    active: local
    group:
      local:
        - local
        - oauth2
      prod:
        - prod
        - oauth2
      test:
        - test
        - oauth2
  config:
    import:
      - classpath:/application-security.yml
